### ISSUE TITLE
Running first time on wsl

### ISSUE THREAD

**Issue by SonGokussj4** [fpgmaas/cookiecutter-uv#25]
**Cookiecutter didn't finish properly**

I've invoked this by running it with `uvx` but it didn't finish properly.

**To Reproduce**

```bash
$ uvx cookiecutter https://github.com/fpgmaas/cookiecutter-uv.git
Installed 22 packages in 13ms
You've downloaded /home/<username>/.cookiecutters/cookiecutter-uv before. Is it okay to delete and re-download it? [y/n]
(y): y
  [1/14] author (Florian Maas): Example User
  [2/14] email (fpgmaas@gmail.com): exampleuser@centrum.cz
  [3/14] author_github_handle (fpgmaas): exampleusre
  [4/14] project_name (example-project): example-project
  [5/14] project_slug (exampleproject):
  [6/14] project_description (This is a template repository for Python projects that use uv for their dependency
management.):
  [7/14] Select include_github_actions
    1 - y
    2 - n
    Choose from [1/2] (1): 2
  [8/14] Select publish_to_pypi
    1 - y
    2 - n
    Choose from [1/2] (1): 1
  [9/14] Select deptry
    1 - y
    2 - n
    Choose from [1/2] (1): 1
  [10/14] Select mkdocs
    1 - y
    2 - n
    Choose from [1/2] (1): 1
  [11/14] Select codecov
    1 - y
    2 - n
    Choose from [1/2] (1): 1
  [12/14] Select dockerfile
    1 - y
    2 - n
    Choose from [1/2] (1): 1
  [13/14] Select devcontainer
    1 - y
    2 - n
    Choose from [1/2] (1): 1
  [14/14] Select open_source_license
    1 - MIT license
    2 - BSD license
    3 - ISC license
    4 - Apache Software License 2.0
    5 - GNU General Public License v3
    6 - Not open source
    Choose from [1/2/3/4/5/6] (1): 1
Traceback (most recent call last):
  File "/home/<username>/.cache/uv/archive-v0/6NewuFPrPLqR5IuggU0rH/bin/cookiecutter", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/<username>/.cache/uv/archive-v0/6NewuFPrPLqR5IuggU0rH/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<username>/.cache/uv/archive-v0/6NewuFPrPLqR5IuggU0rH/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/<username>/.cache/uv/archive-v0/6NewuFPrPLqR5IuggU0rH/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<username>/.cache/uv/archive-v0/6NewuFPrPLqR5IuggU0rH/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<username>/.cache/uv/archive-v0/6NewuFPrPLqR5IuggU0rH/lib/python3.12/site-packages/cookiecutter/cli.py", line 203, in main
    cookiecutter(
  File "/home/<username>/.cache/uv/archive-v0/6NewuFPrPLqR5IuggU0rH/lib/python3.12/site-packages/cookiecutter/main.py", line 182, in cookiecutter
    result = generate_files(
             ^^^^^^^^^^^^^^^
  File "/home/<username>/.cache/uv/archive-v0/6NewuFPrPLqR5IuggU0rH/lib/python3.12/site-packages/cookiecutter/generate.py", line 409, in generate_files
    generate_file(
  File "/home/<username>/.cache/uv/archive-v0/6NewuFPrPLqR5IuggU0rH/lib/python3.12/site-packages/cookiecutter/generate.py", line 227, in generate_file
    fh.write(rendered_file)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc4' in position 211: surrogates not allowed
```

**System [please complete the following information]:**

- OS: e.g. [Windows, WSL2]
- Language Version: [e.g. Python 3.12]
- Virtual environment: [e.g. uv 0.4.29]

**Comment by pablofueros** [comment]
I have successfully recreated the issue on the latest version of Cookiecutter-UV (0.0.10). Try it yourself but this issue could then be closed.
